name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/nextjs-test
          git pull origin main
          sudo docker stop app-main-1 app-main-2 app-main-3 || true
          sudo docker rm app-main-1 app-main-2 app-main-3 || true
          sudo docker rmi main-app-image || true
          sudo docker build -t main-app-image .
          sudo docker run -d -p 3001:3000 --name app-main-1 main-app-image
          sudo docker run -d -p 3002:3000 --name app-main-2 main-app-image
          sudo docker run -d -p 3003:3000 --name app-main-3 main-app-image
        EOF
